/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'email' : IDL.Text,
});
export const Time = IDL.Int;
export const DailyIntention = IDL.Record({ 'date' : Time, 'text' : IDL.Text });
export const DrawnSymbol = IDL.Record({
  'spiritAnimal' : IDL.Text,
  'timestamp' : Time,
});
export const JournalEntry = IDL.Record({
  'title' : IDL.Text,
  'body' : IDL.Text,
  'spiritAnimal' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDrawnSymbol' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createJournalEntry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'deleteJournalEntry' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyIntention' : IDL.Func([], [IDL.Opt(DailyIntention)], ['query']),
  'getDrawHistory' : IDL.Func([], [IDL.Vec(DrawnSymbol)], ['query']),
  'getJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setDailyIntention' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'username' : IDL.Text, 'email' : IDL.Text });
  const Time = IDL.Int;
  const DailyIntention = IDL.Record({ 'date' : Time, 'text' : IDL.Text });
  const DrawnSymbol = IDL.Record({
    'spiritAnimal' : IDL.Text,
    'timestamp' : Time,
  });
  const JournalEntry = IDL.Record({
    'title' : IDL.Text,
    'body' : IDL.Text,
    'spiritAnimal' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDrawnSymbol' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createJournalEntry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'deleteJournalEntry' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyIntention' : IDL.Func([], [IDL.Opt(DailyIntention)], ['query']),
    'getDrawHistory' : IDL.Func([], [IDL.Vec(DrawnSymbol)], ['query']),
    'getJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setDailyIntention' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };